var news=[
  {
    "id": 1,
    "name": "Khan",
    "img": "../images/profile/img1.png",
    "title": "web designer",
    "phone": "1.1",
    "email": "1.1",
    "site": "1.1",
    "dob": "1.1",
    "address": "1.1",
    "hobby1": "1.2",
    "hobby2": "1.2",
    "hobby3": "1.2",
    "skill1": "1.3",
    "skill2": "1.3",
    "skill3": "1.3",
    "income": "20000"
  },
  {
    "id": 2,
    "name": "accusamus beatae",
    "img": "../images/profile/img(2).png",
    "title": "web designer",
    "phone": "2",
    "email": "2",
    "site": "2",
    "dob": "2",
    "address": "2",
    "hobby1": "2",
    "hobby2": "2",
    "hobby3": "2",
    "skill1": "2",
    "skill2": "2",
    "skill3": "2",
    "income": "10000"
  },
  {
    "id": 3,
    "name": "pro",
    "img": "https://via.placeholder.com/600/92c952",
    "title": "graphics designer",
    "phone": "3",
    "email": "3",
    "site": "3",
    "dob": "3",
    "address": "3",
    "hobby1": "3",
    "hobby2": "3",
    "hobby3": "3",
    "skill1": "3",
    "skill2": "3",
    "skill3": "3",
    "income": "30000"
  }
]
export default news;